### ISSUE TITLE
how to 3D visualization

### ISSUE THREAD

**Issue by xinsheng44** [sanketx/mitochondria_segmentation#1]
Thank you for your open source project.

At present, I am segmenting the mitochondria of scanning electron microscope, and then forming mrc based on the segmented image for 3D visualization.

But there is no suitable visualization tool found at present, I see [picture] (https://github.com/sanketx/mitochondria_segmentation/blob/main/media/cover_1920x1080.jpg) in your project，How is this visualized？

Looking forward to your reply！

**Comment by sanketx** [comment]
I used [Chimera X](https://www.cgl.ucsf.edu/chimerax/) to perform the visualizations. I used it to load up the tomograms and the corresponding segmentation masks, along with some custom scripts to color the granules. Images from multiple mitochondria were composited using Canva to create the final image you linked.
